version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: blog_postgres
    environment:
      POSTGRES_DB: blog_db_8gzl
      POSTGRES_USER: blog_db_8gzl_user
      POSTGRES_PASSWORD: Xofj3tqTccxuMogErpupYPyZBTpFnngh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network

  backend:
    build: .
    container_name: blog_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blog_db_8gzl
      SPRING_DATASOURCE_USERNAME: blog_db_8gzl_user
      SPRING_DATASOURCE_PASSWORD: Xofj3tqTccxuMogErpupYPyZBTpFnngh
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
      - blog_network

volumes:
  postgres_data:

networks:
  blog_network:
